#!/usr/bin/env python3
import argparse
import sys

import numpy as np


def compute_depths(f):
    depths = np.loadtxt(f, dtype=np.int64)

    single_increasing = np.sum(depths[1:] > depths[:-1])
    print(f"1) {single_increasing}")

    triples_sum = np.lib.stride_tricks.sliding_window_view(depths, 3).sum(axis=-1)
    triple_increasing = np.sum(triples_sum[1:] > triples_sum[:-1])
    print(f"2) {triple_increasing}")


def main(argv=None):
    parser = argparse.ArgumentParser(description="01 Sonar Depths")
    parser.add_argument("file", type=argparse.FileType("r"), default=sys.stdin)
    args = parser.parse_args(args=argv)

    compute_depths(args.file)


if __name__ == "__main__":
    main()
