#!/usr/bin/env python3
import argparse
import sys

import numpy as np


def main(argv=None):
    parser = argparse.ArgumentParser("Among Us")
    parser.add_argument("file", type=argparse.FileType("r"), default=sys.stdin)
    parser.add_argument("-e", "--epochs", default=80, type=int)
    args = parser.parse_args(args=argv)

    age = np.loadtxt(args.file, delimiter=",", dtype=np.uint64)
    state = np.zeros(9, dtype=np.uint64)
    np.add.at(state, age, 1)

    for i in range(args.epochs):
        new = state[0]
        state[:-1] = state[1:]
        state[6] += new
        state[8] = new

    print(f"1) {np.sum(state)}")


if __name__ == "__main__":
    main()
