#!/usr/bin/env python3
import argparse
import sys

import numpy as np


def main(argv=None):
    parser = argparse.ArgumentParser("Santa Claws")
    parser.add_argument("file", type=argparse.FileType("r"), default=sys.stdin)
    args = parser.parse_args(args=argv)

    x = np.loadtxt(args.file, delimiter=",", dtype=np.int64)
    x_0 = np.arange(x.min(), x.max() + 1, dtype=np.int64)
    dx = np.abs(x - x_0.reshape(-1, 1))

    cost_const = dx.sum(axis=1)
    cost_arithmetic = ((dx * (dx + 1)) // 2).sum(axis=1)

    print(f"1) {cost_const.min()}")
    print(f"2) {cost_arithmetic.min()}")


if __name__ == "__main__":
    main()
